{
	"version": 1785782131,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/prenten1-sheet0.png",
		"images/prenten1-sheet1.png",
		"images/start-sheet0.png",
		"images/wijzer-sheet0.png",
		"images/richting-sheet0.png",
		"images/richting-sheet1.png",
		"images/controle-sheet0.png",
		"images/ja-sheet0.png",
		"images/neen-sheet0.png",
		"images/neen-sheet1.png",
		"images/bravo-sheet0.png",
		"images/bravo-sheet1.png",
		"images/resume-sheet0.png",
		"images/home-sheet0.png",
		"images/prenten2-sheet0.png",
		"images/prenten3-sheet0.png",
		"images/prenten4-sheet0.png",
		"images/tiledbackground.png",
		"images/reeks2-sheet0.png",
		"images/reeks1-sheet0.png",
		"images/reeks3-sheet0.png",
		"images/reeks4-sheet0.png",
		"images/waiting2-sheet0.png",
		"images/hoofdmenu-sheet0.png",
		"images/tiledbackground2.png",
		"media/arend.m4a",
		"media/arend.ogg",
		"media/dolfijn.m4a",
		"media/dolfijn.ogg",
		"media/ezel.m4a",
		"media/ezel.ogg",
		"media/giraf.m4a",
		"media/giraf.ogg",
		"media/ijsbeer.m4a",
		"media/ijsbeer.ogg",
		"media/kameel.m4a",
		"media/kameel.ogg",
		"media/kikvors.m4a",
		"media/kikvors.ogg",
		"media/konijn.m4a",
		"media/konijn.ogg",
		"media/kuiken.m4a",
		"media/kuiken.ogg",
		"media/neushoorn.m4a",
		"media/neushoorn.ogg",
		"media/nijlpaard.m4a",
		"media/nijlpaard.ogg",
		"media/panda.m4a",
		"media/panda.ogg",
		"media/schildpad.m4a",
		"media/schildpad.ogg",
		"media/sprinkhaan.m4a",
		"media/sprinkhaan.ogg",
		"media/tijger.m4a",
		"media/tijger.ogg",
		"media/varken.m4a",
		"media/varken.ogg",
		"media/vlinder.m4a",
		"media/vlinder.ogg",
		"media/walvis.m4a",
		"media/walvis.ogg",
		"media/zebra.m4a",
		"media/zebra.ogg",
		"media/zeester.m4a",
		"media/zeester.ogg",
		"media/boksen.m4a",
		"media/boksen.ogg",
		"media/bowling.m4a",
		"media/bowling.ogg",
		"media/dansen.m4a",
		"media/dansen.ogg",
		"media/duiken.m4a",
		"media/duiken.ogg",
		"media/fietsen.m4a",
		"media/fietsen.ogg",
		"media/handbal.m4a",
		"media/handbal.ogg",
		"media/hockey.m4a",
		"media/hockey.ogg",
		"media/judo.m4a",
		"media/judo.ogg",
		"media/karting.m4a",
		"media/karting.ogg",
		"media/klimmen.m4a",
		"media/klimmen.ogg",
		"media/lopen.m4a",
		"media/lopen.ogg",
		"media/rugby.m4a",
		"media/rugby.ogg",
		"media/schaatsen.m4a",
		"media/schaatsen.ogg",
		"media/schermen.m4a",
		"media/schermen.ogg",
		"media/skiën.m4a",
		"media/skiën.ogg",
		"media/tennis.m4a",
		"media/tennis.ogg",
		"media/turnen.m4a",
		"media/turnen.ogg",
		"media/voetbal.m4a",
		"media/voetbal.ogg",
		"media/zeilen.m4a",
		"media/zeilen.ogg",
		"media/zwemmen.m4a",
		"media/zwemmen.ogg",
		"media/hij bouwt.m4a",
		"media/hij bouwt.ogg",
		"media/hij breekt.m4a",
		"media/hij breekt.ogg",
		"media/hij brult.m4a",
		"media/hij brult.ogg",
		"media/hij hoest.m4a",
		"media/hij hoest.ogg",
		"media/hij kruipt.m4a",
		"media/hij kruipt.ogg",
		"media/hij rijdt.m4a",
		"media/hij rijdt.ogg",
		"media/hij snijdt.m4a",
		"media/hij snijdt.ogg",
		"media/hij surft.m4a",
		"media/hij surft.ogg",
		"media/hij vangt.m4a",
		"media/hij vangt.ogg",
		"media/hij vecht.m4a",
		"media/hij vecht.ogg",
		"media/hij vraagt.m4a",
		"media/hij vraagt.ogg",
		"media/zij droomt.m4a",
		"media/zij droomt.ogg",
		"media/zij kleurt.m4a",
		"media/zij kleurt.ogg",
		"media/zij klimt.m4a",
		"media/zij klimt.ogg",
		"media/zij knipt.m4a",
		"media/zij knipt.ogg",
		"media/zij kuist.m4a",
		"media/zij kuist.ogg",
		"media/zij schrijft.m4a",
		"media/zij schrijft.ogg",
		"media/zij speelt.m4a",
		"media/zij speelt.ogg",
		"media/zij werpt.m4a",
		"media/zij werpt.ogg",
		"media/zij zwemt.m4a",
		"media/zij zwemt.ogg",
		"media/aardbei.m4a",
		"media/aardbei.ogg",
		"media/appels.m4a",
		"media/appels.ogg",
		"media/banaan.m4a",
		"media/banaan.ogg",
		"media/bloemkool.m4a",
		"media/bloemkool.ogg",
		"media/bonen.m4a",
		"media/bonen.ogg",
		"media/citroen.m4a",
		"media/citroen.ogg",
		"media/druiven.m4a",
		"media/druiven.ogg",
		"media/erwten.m4a",
		"media/erwten.ogg",
		"media/kersen.m4a",
		"media/kersen.ogg",
		"media/kiwi's.m4a",
		"media/kiwi's.ogg",
		"media/maïs.m4a",
		"media/maïs.ogg",
		"media/peren.m4a",
		"media/peren.ogg",
		"media/perzik.m4a",
		"media/perzik.ogg",
		"media/pompoen.m4a",
		"media/pompoen.ogg",
		"media/pruimen.m4a",
		"media/pruimen.ogg",
		"media/radijs.m4a",
		"media/radijs.ogg",
		"media/spruiten.m4a",
		"media/spruiten.ogg",
		"media/tomaat.m4a",
		"media/tomaat.ogg",
		"media/witloof.m4a",
		"media/witloof.ogg",
		"media/wortel.m4a",
		"media/wortel.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}